export { default as HomeLayout } from './HomeLayout';
export { default as LandingPage } from './LandingPage';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Student } from './Student';
export { default as DashboardStudent } from './DashboardStudent';
export { default as Error } from './Error';
export { default as About } from './About';
export { default as Stuffs } from './Stuffs';
export { default as Compose} from './Compose';
export { default as Admin} from './Admin';
export { default as AdminLayout} from './AdminLayout';